import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/** Where attachment bytes live. Local disk now; an S3-compatible backend can implement this later. */
export interface FileStorage {
  put(key: string, data: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array>;
  delete(key: string): Promise<void>;
}

export class LocalFileStorage implements FileStorage {
  constructor(private readonly root: string) {}

  private resolve(key: string): string {
    // Keys are generated by newStorageKey(); refuse anything that could escape the root.
    if (!/^[a-z0-9/-]+$/.test(key) || key.includes("..") || key.startsWith("/")) {
      throw new Error(`Invalid storage key: ${key}`);
    }
    return path.join(this.root, ...key.split("/"));
  }

  async put(key: string, data: Uint8Array): Promise<void> {
    const file = this.resolve(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, data, { flag: "wx" });
  }

  async get(key: string): Promise<Uint8Array> {
    return new Uint8Array(await readFile(this.resolve(key)));
  }

  async delete(key: string): Promise<void> {
    await rm(this.resolve(key), { force: true });
  }
}

/** A new random key, grouped by month so no single directory grows without bound. */
export function newStorageKey(now = new Date()): string {
  const month = `${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
  return `${month}/${randomUUID()}`;
}

const globalForStorage = globalThis as unknown as { peteyStorage?: FileStorage };

/** The configured storage: STORAGE_DIR, or ./.data/uploads under the working directory. */
export function getStorage(): FileStorage {
  globalForStorage.peteyStorage ??= new LocalFileStorage(
    path.resolve(process.env.STORAGE_DIR || path.join(process.cwd(), ".data", "uploads")),
  );
  return globalForStorage.peteyStorage;
}
